### ISSUE TITLE
Create node module

### ISSUE THREAD

**Issue by p-a-s-c-a-l** [clarity-h2020/csis-helpers-js#1]
Create a node module out of a few simple libs. Looks like a manageable task - but not with modern JS frameworks.

Unfortunately, the [unmaintainable web dev stack](https://hackernoon.com/how-it-feels-to-learn-javascript-in-2016-d3a717dd577f) and the related build processes are ridiculously complex and intransparent.

**Comment by p-a-s-c-a-l** [comment]
```
 FAIL  src/__tests__/CSISHelpers.test.js
  ● Test suite failed to run

    ReferenceError: regeneratorRuntime is not defined

      2 | import log from 'loglevel';
      3 | //import CSISHelpers from './../logic/CSISHelpers.js';
    > 4 | import CSISHelpers from 'csis-helpers-js';
        | ^
      5 | import express from 'express'
      6 | import apiResponseStudy from './../__fixtures__/study.json';
      7 | import apiResponseDataPackage from './../__fixtures__/dataPackage.json';
```

**Comment by p-a-s-c-a-l** [comment]
```
 FAIL  src/__tests__/CSISHelpers.test.js (7.825s)
  ● test extract study area from study json

    TypeError: Cannot read property 'extractStudyAreaFromStudyGroupNode' of undefined

      45 |     expect(response.data.data[0]).not.toBeNull();
      46 | 
    > 47 |     const studyAreaJson = CSISHelpers.extractStudyAreaFromStudyGroupNode(response.data.data[0]);
         |                                       ^
      48 |     expect(studyAreaJson).toEqual(studyArea);
      49 |     done();
      50 | });

      at Object.extractStudyAreaFromStudyGroupNode (src/__tests__/CSISHelpers.test.js:47:39)
```
But **WHY**? That's the module definition:

```js
var CSISHelpers$1 = /*#__PURE__*/Object.freeze({
  'default': CSISHelpers,
  extractEmikatIdFromStudyGroupNode: extractEmikatIdFromStudyGroupNode,
  getIncludedObject: getIncludedObject,
  filterResourcesbyTagName: filterResourcesbyTagName,
  filterResourcesbyReferenceType: filterResourcesbyReferenceType,
  extractReferencesfromResource: extractReferencesfromResource,
  extractTagsfromResource: extractTagsfromResource,
  extractStudyAreaFromStudyGroupNode: extractStudyAreaFromStudyGroupNode
});

exports.CSISHelpers = CSISHelpers$1;
```

**Comment by p-a-s-c-a-l** [comment]
Forget yarn link, it's less useful than expected: https://github.com/yarnpkg/yarn/issues/2914

**Comment by p-a-s-c-a-l** [comment]
Trial and error: https://stackoverflow.com/a/53974034

```
[!] (plugin babel) Error: Runtime helpers are not enabled. Either exclude the transform-runtime Babel plugin or pass the `runtimeHelpers: true` option. See https://github.com/rollup/rollup-plugin-babel#configuring-babel for more information
src\index.js
Error: Runtime helpers are not enabled. Either exclude the transform-runtime Babel plugin or pass the `runtimeHelpers: true` option. See https://github.com/rollup/rollup-plugin-babel#configuring-babel for more information
    at error (C:\git_work\CLARITY\csis-helpers-js\node_modules\rollup\dist\rollup.js:9435:30)
    at throwPluginError (C:\git_work\CLARITY\csis-helpers-js\node_modules\rollup\dist\rollup.js:15754:12)
    at Object.error (C:\git_work\CLARITY\csis-helpers-js\node_modules\rollup\dist\rollup.js:15809:24)
    at Object.error (C:\git_work\CLARITY\csis-helpers-js\node_modules\rollup\dist\rollup.js:16192:38)
    at C:\git_work\CLARITY\csis-helpers-js\node_modules\rollup-plugin-babel\src\index.js:103:12

error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by p-a-s-c-a-l** [comment]
No, none of the [hacks on top of hacks](https://www.quirksmode.org/blog/archives/2016/09/web_development.html) seems to work:

```
 FAIL  src/__tests__/CSISHelpers.test.js
  ● test extract study area from study json

    TypeError: Cannot read property 'extractStudyAreaFromStudyGroupNode' of undefined
```

**Comment by p-a-s-c-a-l** [comment]
OMG! No default export in module! 

`import CSISHelpers from 'csis-helpers-js';` vs. `import {CSISHelpers} from `csis-helpers-js';`

See https://stackoverflow.com/questions/36795819/when-should-i-use-curly-braces-for-es6-import/36796281#36796281

**Comment by p-a-s-c-a-l** [comment]
This is absolutely ridiculous:

```
Debugger listening on ws://127.0.0.1:27924/df00fd42-b258-41e4-8e8c-abd6179bbd41
For help, see: https://nodejs.org/en/docs/inspector
Debugger attached.
 FAIL  src/__tests__/CSISRemoteHelpers.test.js
  ● Test suite failed to run

    C:\git_work\CLARITY\csis-helpers-js\src\__tests__\CSISRemoteHelpers.test.js:1
    ({"Object.<anonymous>":function(module,exports,require,__dirname,__filename,global,jest){import _regeneratorRuntime from "@babel/runtime/regenerator";
                                                                                                    ^^^^^^^^^^^^^^^^^^^

    SyntaxError: Unexpected identifier

      at ScriptTransformer._transformAndBuildScript (node_modules/@jest/transform/build/ScriptTransformer.js:537:17)
      at ScriptTransformer.transform (node_modules/@jest/transform/build/ScriptTransformer.js:579:25)

Test Suites: 1 failed, 1 total
Tests:       0 total
Snapshots:   0 total
Time:        3.012s
```

The solution *may* be found [here](https://stackoverflow.com/questions/33527653/babel-6-regeneratorruntime-is-not-defined).

**Comment by p-a-s-c-a-l** [comment]
WARNING! BEWARE OF A NEW CHROME "FEATURE"
IF YOU DON'T SEE DEBUG MESSAGES IN CHROME CONSOLE, TRY

- https://github.com/pimterry/loglevel/issues/111#issuecomment-321818160
- https://stackoverflow.com/questions/52730747/google-chrome-console-does-not-allow-log-level-change

**Comment by p-a-s-c-a-l** [comment]
done
