### ISSUE TITLE
Tests

### ISSUE THREAD

**Issue by p-a-s-c-a-l** [clarity-h2020/csis-helpers-js#6]
Add some tests :-)

**Comment by p-a-s-c-a-l** [comment]
The idea seems brilliant: Programmatically import headers fixture and ...

```js
/**
 * @type {Object[]}
 */
var headers = undefined;
try {
    import('./../__fixtures__/csisHeaders.js').then(
        (module) => { headers = module.default; log.info('headers.js fixture found, executing remote API tests'); },
        (error) => { log.info('csisHeaders.js is not present, skipping remote API tests'); }
    );
} catch (error) {
    //ignore
}
```

... skip tests if not present:

```js
describe('Remote API tests with authentication', () => {

    // skip tests if local headers file not available
    if (!headers) {
        it.only('no headers.js fixture found, skipping remote API tests', () => {
            log.warn('no headers.js fixture found, skipping remote API tests');
        });
    }
   
   // tests that require headers
   it(...
``` 

Unfortunately, jest doesn't support **asynchronously** skipping tests. 

So, back to the 90ties and use ENV vars?

**Comment by p-a-s-c-a-l** [comment]
"GREAT": No log output in JEST tests, and none of the proposed ["solutions"](https://github.com/facebook/jest/issues/2441) works.

**Comment by p-a-s-c-a-l** [comment]
"GREAT": No debugging of Jest tests with Jest VS-Code Plugin:
`` 
Debugger listening on ws://127.0.0.1:17589/672468c9-4c74-4f01-a090-3b5c67df6ac3
For help, see: https://nodejs.org/en/docs/inspector
Debugger attached.
 FAIL  src/__tests__/CSISRemoteHelpers.test.js
 Test suite failed to run
    C:\git_work\CLARITY\csis-helpers-js\src\__tests__\CSISRemoteHelpers.test.js:1
    ({"Object.<anonymous>":function(module,exports,require,__dirname,__filename,global,jest){import _regeneratorRuntime from "@babel/runtime/regenerator";
                                                                                                    ^^^^^^^^^^^^^^^^^^^
SyntaxError: Unexpected identifier

      at ScriptTransformer._transformAndBuildScript (node_modules/@jest/transform/build/ScriptTransformer.js:537:17)
      at ScriptTransformer.transform (node_modules/@jest/transform/build/ScriptTransformer.js:579:25)

Test Suites: 1 failed, 1 total
Tests:       0 total
Snapshots:   0 total
Time:        2.603s
``

**Comment by p-a-s-c-a-l** [comment]
export tests to be reused in other projects - of course this doesn't work! Exported tests take forever to complete because they are executed for each test suite.

**Comment by p-a-s-c-a-l** [comment]
done
